import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import SideBars from "./components/SideBars";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-50 min-h-screen flex flex-col">
          {/* Header en haut */}
          <Header />

          {/* Container principal */}
          <div className="flex flex-1 pt-20">
            {/* Sidebar */}
            <SideBars />

            {/* Contenu */}
            <main className="flex-1 ml-30">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
